/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LeaderboardEventIdRouteImport } from './routes/leaderboard.$eventId'
import { Route as AuthFinishRouteImport } from './routes/auth.finish'
import { Route as AuthenticatedOrganizerIndexRouteImport } from './routes/_authenticated/organizer/index'
import { Route as AuthenticatedParticipantEventIdRouteImport } from './routes/_authenticated/participant.$eventId'
import { Route as AuthenticatedOrganizerDashboardRouteImport } from './routes/_authenticated/organizer/dashboard'
import { Route as AuthenticatedJuryEventIdRouteImport } from './routes/_authenticated/jury.$eventId'
import { Route as AuthenticatedOrganizerEventsIndexRouteImport } from './routes/_authenticated/organizer/events.index'
import { Route as AuthenticatedOrganizerEventsNewRouteImport } from './routes/_authenticated/organizer/events.new'
import { Route as AuthenticatedOrganizerEventsIdRouteImport } from './routes/_authenticated/organizer/events.$id'
import { Route as AuthenticatedOrganizerEventsIdIndexRouteImport } from './routes/_authenticated/organizer/events.$id.index'
import { Route as AuthenticatedOrganizerEventsIdTeamsRouteImport } from './routes/_authenticated/organizer/events.$id.teams'
import { Route as AuthenticatedOrganizerEventsIdSubmissionsRouteImport } from './routes/_authenticated/organizer/events.$id.submissions'
import { Route as AuthenticatedOrganizerEventsIdRegistrationsRouteImport } from './routes/_authenticated/organizer/events.$id.registrations'
import { Route as AuthenticatedOrganizerEventsIdLeaderboardRouteImport } from './routes/_authenticated/organizer/events.$id.leaderboard'
import { Route as AuthenticatedOrganizerEventsIdJuryRouteImport } from './routes/_authenticated/organizer/events.$id.jury'
import { Route as AuthenticatedOrganizerEventsIdJudgingRouteImport } from './routes/_authenticated/organizer/events.$id.judging'
import { Route as AuthenticatedOrganizerEventsIdCertificatesRouteImport } from './routes/_authenticated/organizer/events.$id.certificates'
import { Route as AuthenticatedOrganizerEventsIdAnalyticsRouteImport } from './routes/_authenticated/organizer/events.$id.analytics'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardEventIdRoute = LeaderboardEventIdRouteImport.update({
  id: '/leaderboard/$eventId',
  path: '/leaderboard/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthFinishRoute = AuthFinishRouteImport.update({
  id: '/auth/finish',
  path: '/auth/finish',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOrganizerIndexRoute =
  AuthenticatedOrganizerIndexRouteImport.update({
    id: '/organizer/',
    path: '/organizer/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedParticipantEventIdRoute =
  AuthenticatedParticipantEventIdRouteImport.update({
    id: '/participant/$eventId',
    path: '/participant/$eventId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrganizerDashboardRoute =
  AuthenticatedOrganizerDashboardRouteImport.update({
    id: '/organizer/dashboard',
    path: '/organizer/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedJuryEventIdRoute =
  AuthenticatedJuryEventIdRouteImport.update({
    id: '/jury/$eventId',
    path: '/jury/$eventId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrganizerEventsIndexRoute =
  AuthenticatedOrganizerEventsIndexRouteImport.update({
    id: '/organizer/events/',
    path: '/organizer/events/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrganizerEventsNewRoute =
  AuthenticatedOrganizerEventsNewRouteImport.update({
    id: '/organizer/events/new',
    path: '/organizer/events/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrganizerEventsIdRoute =
  AuthenticatedOrganizerEventsIdRouteImport.update({
    id: '/organizer/events/$id',
    path: '/organizer/events/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrganizerEventsIdIndexRoute =
  AuthenticatedOrganizerEventsIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedOrganizerEventsIdRoute,
  } as any)
const AuthenticatedOrganizerEventsIdTeamsRoute =
  AuthenticatedOrganizerEventsIdTeamsRouteImport.update({
    id: '/teams',
    path: '/teams',
    getParentRoute: () => AuthenticatedOrganizerEventsIdRoute,
  } as any)
const AuthenticatedOrganizerEventsIdSubmissionsRoute =
  AuthenticatedOrganizerEventsIdSubmissionsRouteImport.update({
    id: '/submissions',
    path: '/submissions',
    getParentRoute: () => AuthenticatedOrganizerEventsIdRoute,
  } as any)
const AuthenticatedOrganizerEventsIdRegistrationsRoute =
  AuthenticatedOrganizerEventsIdRegistrationsRouteImport.update({
    id: '/registrations',
    path: '/registrations',
    getParentRoute: () => AuthenticatedOrganizerEventsIdRoute,
  } as any)
const AuthenticatedOrganizerEventsIdLeaderboardRoute =
  AuthenticatedOrganizerEventsIdLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => AuthenticatedOrganizerEventsIdRoute,
  } as any)
const AuthenticatedOrganizerEventsIdJuryRoute =
  AuthenticatedOrganizerEventsIdJuryRouteImport.update({
    id: '/jury',
    path: '/jury',
    getParentRoute: () => AuthenticatedOrganizerEventsIdRoute,
  } as any)
const AuthenticatedOrganizerEventsIdJudgingRoute =
  AuthenticatedOrganizerEventsIdJudgingRouteImport.update({
    id: '/judging',
    path: '/judging',
    getParentRoute: () => AuthenticatedOrganizerEventsIdRoute,
  } as any)
const AuthenticatedOrganizerEventsIdCertificatesRoute =
  AuthenticatedOrganizerEventsIdCertificatesRouteImport.update({
    id: '/certificates',
    path: '/certificates',
    getParentRoute: () => AuthenticatedOrganizerEventsIdRoute,
  } as any)
const AuthenticatedOrganizerEventsIdAnalyticsRoute =
  AuthenticatedOrganizerEventsIdAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedOrganizerEventsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/auth/finish': typeof AuthFinishRoute
  '/leaderboard/$eventId': typeof LeaderboardEventIdRoute
  '/jury/$eventId': typeof AuthenticatedJuryEventIdRoute
  '/organizer/dashboard': typeof AuthenticatedOrganizerDashboardRoute
  '/participant/$eventId': typeof AuthenticatedParticipantEventIdRoute
  '/organizer/': typeof AuthenticatedOrganizerIndexRoute
  '/organizer/events/$id': typeof AuthenticatedOrganizerEventsIdRouteWithChildren
  '/organizer/events/new': typeof AuthenticatedOrganizerEventsNewRoute
  '/organizer/events/': typeof AuthenticatedOrganizerEventsIndexRoute
  '/organizer/events/$id/analytics': typeof AuthenticatedOrganizerEventsIdAnalyticsRoute
  '/organizer/events/$id/certificates': typeof AuthenticatedOrganizerEventsIdCertificatesRoute
  '/organizer/events/$id/judging': typeof AuthenticatedOrganizerEventsIdJudgingRoute
  '/organizer/events/$id/jury': typeof AuthenticatedOrganizerEventsIdJuryRoute
  '/organizer/events/$id/leaderboard': typeof AuthenticatedOrganizerEventsIdLeaderboardRoute
  '/organizer/events/$id/registrations': typeof AuthenticatedOrganizerEventsIdRegistrationsRoute
  '/organizer/events/$id/submissions': typeof AuthenticatedOrganizerEventsIdSubmissionsRoute
  '/organizer/events/$id/teams': typeof AuthenticatedOrganizerEventsIdTeamsRoute
  '/organizer/events/$id/': typeof AuthenticatedOrganizerEventsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/auth/finish': typeof AuthFinishRoute
  '/leaderboard/$eventId': typeof LeaderboardEventIdRoute
  '/jury/$eventId': typeof AuthenticatedJuryEventIdRoute
  '/organizer/dashboard': typeof AuthenticatedOrganizerDashboardRoute
  '/participant/$eventId': typeof AuthenticatedParticipantEventIdRoute
  '/organizer': typeof AuthenticatedOrganizerIndexRoute
  '/organizer/events/new': typeof AuthenticatedOrganizerEventsNewRoute
  '/organizer/events': typeof AuthenticatedOrganizerEventsIndexRoute
  '/organizer/events/$id/analytics': typeof AuthenticatedOrganizerEventsIdAnalyticsRoute
  '/organizer/events/$id/certificates': typeof AuthenticatedOrganizerEventsIdCertificatesRoute
  '/organizer/events/$id/judging': typeof AuthenticatedOrganizerEventsIdJudgingRoute
  '/organizer/events/$id/jury': typeof AuthenticatedOrganizerEventsIdJuryRoute
  '/organizer/events/$id/leaderboard': typeof AuthenticatedOrganizerEventsIdLeaderboardRoute
  '/organizer/events/$id/registrations': typeof AuthenticatedOrganizerEventsIdRegistrationsRoute
  '/organizer/events/$id/submissions': typeof AuthenticatedOrganizerEventsIdSubmissionsRoute
  '/organizer/events/$id/teams': typeof AuthenticatedOrganizerEventsIdTeamsRoute
  '/organizer/events/$id': typeof AuthenticatedOrganizerEventsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/auth/finish': typeof AuthFinishRoute
  '/leaderboard/$eventId': typeof LeaderboardEventIdRoute
  '/_authenticated/jury/$eventId': typeof AuthenticatedJuryEventIdRoute
  '/_authenticated/organizer/dashboard': typeof AuthenticatedOrganizerDashboardRoute
  '/_authenticated/participant/$eventId': typeof AuthenticatedParticipantEventIdRoute
  '/_authenticated/organizer/': typeof AuthenticatedOrganizerIndexRoute
  '/_authenticated/organizer/events/$id': typeof AuthenticatedOrganizerEventsIdRouteWithChildren
  '/_authenticated/organizer/events/new': typeof AuthenticatedOrganizerEventsNewRoute
  '/_authenticated/organizer/events/': typeof AuthenticatedOrganizerEventsIndexRoute
  '/_authenticated/organizer/events/$id/analytics': typeof AuthenticatedOrganizerEventsIdAnalyticsRoute
  '/_authenticated/organizer/events/$id/certificates': typeof AuthenticatedOrganizerEventsIdCertificatesRoute
  '/_authenticated/organizer/events/$id/judging': typeof AuthenticatedOrganizerEventsIdJudgingRoute
  '/_authenticated/organizer/events/$id/jury': typeof AuthenticatedOrganizerEventsIdJuryRoute
  '/_authenticated/organizer/events/$id/leaderboard': typeof AuthenticatedOrganizerEventsIdLeaderboardRoute
  '/_authenticated/organizer/events/$id/registrations': typeof AuthenticatedOrganizerEventsIdRegistrationsRoute
  '/_authenticated/organizer/events/$id/submissions': typeof AuthenticatedOrganizerEventsIdSubmissionsRoute
  '/_authenticated/organizer/events/$id/teams': typeof AuthenticatedOrganizerEventsIdTeamsRoute
  '/_authenticated/organizer/events/$id/': typeof AuthenticatedOrganizerEventsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/auth/finish'
    | '/leaderboard/$eventId'
    | '/jury/$eventId'
    | '/organizer/dashboard'
    | '/participant/$eventId'
    | '/organizer/'
    | '/organizer/events/$id'
    | '/organizer/events/new'
    | '/organizer/events/'
    | '/organizer/events/$id/analytics'
    | '/organizer/events/$id/certificates'
    | '/organizer/events/$id/judging'
    | '/organizer/events/$id/jury'
    | '/organizer/events/$id/leaderboard'
    | '/organizer/events/$id/registrations'
    | '/organizer/events/$id/submissions'
    | '/organizer/events/$id/teams'
    | '/organizer/events/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/auth/finish'
    | '/leaderboard/$eventId'
    | '/jury/$eventId'
    | '/organizer/dashboard'
    | '/participant/$eventId'
    | '/organizer'
    | '/organizer/events/new'
    | '/organizer/events'
    | '/organizer/events/$id/analytics'
    | '/organizer/events/$id/certificates'
    | '/organizer/events/$id/judging'
    | '/organizer/events/$id/jury'
    | '/organizer/events/$id/leaderboard'
    | '/organizer/events/$id/registrations'
    | '/organizer/events/$id/submissions'
    | '/organizer/events/$id/teams'
    | '/organizer/events/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/auth/finish'
    | '/leaderboard/$eventId'
    | '/_authenticated/jury/$eventId'
    | '/_authenticated/organizer/dashboard'
    | '/_authenticated/participant/$eventId'
    | '/_authenticated/organizer/'
    | '/_authenticated/organizer/events/$id'
    | '/_authenticated/organizer/events/new'
    | '/_authenticated/organizer/events/'
    | '/_authenticated/organizer/events/$id/analytics'
    | '/_authenticated/organizer/events/$id/certificates'
    | '/_authenticated/organizer/events/$id/judging'
    | '/_authenticated/organizer/events/$id/jury'
    | '/_authenticated/organizer/events/$id/leaderboard'
    | '/_authenticated/organizer/events/$id/registrations'
    | '/_authenticated/organizer/events/$id/submissions'
    | '/_authenticated/organizer/events/$id/teams'
    | '/_authenticated/organizer/events/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  AuthFinishRoute: typeof AuthFinishRoute
  LeaderboardEventIdRoute: typeof LeaderboardEventIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard/$eventId': {
      id: '/leaderboard/$eventId'
      path: '/leaderboard/$eventId'
      fullPath: '/leaderboard/$eventId'
      preLoaderRoute: typeof LeaderboardEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/finish': {
      id: '/auth/finish'
      path: '/auth/finish'
      fullPath: '/auth/finish'
      preLoaderRoute: typeof AuthFinishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/organizer/': {
      id: '/_authenticated/organizer/'
      path: '/organizer'
      fullPath: '/organizer/'
      preLoaderRoute: typeof AuthenticatedOrganizerIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/participant/$eventId': {
      id: '/_authenticated/participant/$eventId'
      path: '/participant/$eventId'
      fullPath: '/participant/$eventId'
      preLoaderRoute: typeof AuthenticatedParticipantEventIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/organizer/dashboard': {
      id: '/_authenticated/organizer/dashboard'
      path: '/organizer/dashboard'
      fullPath: '/organizer/dashboard'
      preLoaderRoute: typeof AuthenticatedOrganizerDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jury/$eventId': {
      id: '/_authenticated/jury/$eventId'
      path: '/jury/$eventId'
      fullPath: '/jury/$eventId'
      preLoaderRoute: typeof AuthenticatedJuryEventIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/organizer/events/': {
      id: '/_authenticated/organizer/events/'
      path: '/organizer/events'
      fullPath: '/organizer/events/'
      preLoaderRoute: typeof AuthenticatedOrganizerEventsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/organizer/events/new': {
      id: '/_authenticated/organizer/events/new'
      path: '/organizer/events/new'
      fullPath: '/organizer/events/new'
      preLoaderRoute: typeof AuthenticatedOrganizerEventsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/organizer/events/$id': {
      id: '/_authenticated/organizer/events/$id'
      path: '/organizer/events/$id'
      fullPath: '/organizer/events/$id'
      preLoaderRoute: typeof AuthenticatedOrganizerEventsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/organizer/events/$id/': {
      id: '/_authenticated/organizer/events/$id/'
      path: '/'
      fullPath: '/organizer/events/$id/'
      preLoaderRoute: typeof AuthenticatedOrganizerEventsIdIndexRouteImport
      parentRoute: typeof AuthenticatedOrganizerEventsIdRoute
    }
    '/_authenticated/organizer/events/$id/teams': {
      id: '/_authenticated/organizer/events/$id/teams'
      path: '/teams'
      fullPath: '/organizer/events/$id/teams'
      preLoaderRoute: typeof AuthenticatedOrganizerEventsIdTeamsRouteImport
      parentRoute: typeof AuthenticatedOrganizerEventsIdRoute
    }
    '/_authenticated/organizer/events/$id/submissions': {
      id: '/_authenticated/organizer/events/$id/submissions'
      path: '/submissions'
      fullPath: '/organizer/events/$id/submissions'
      preLoaderRoute: typeof AuthenticatedOrganizerEventsIdSubmissionsRouteImport
      parentRoute: typeof AuthenticatedOrganizerEventsIdRoute
    }
    '/_authenticated/organizer/events/$id/registrations': {
      id: '/_authenticated/organizer/events/$id/registrations'
      path: '/registrations'
      fullPath: '/organizer/events/$id/registrations'
      preLoaderRoute: typeof AuthenticatedOrganizerEventsIdRegistrationsRouteImport
      parentRoute: typeof AuthenticatedOrganizerEventsIdRoute
    }
    '/_authenticated/organizer/events/$id/leaderboard': {
      id: '/_authenticated/organizer/events/$id/leaderboard'
      path: '/leaderboard'
      fullPath: '/organizer/events/$id/leaderboard'
      preLoaderRoute: typeof AuthenticatedOrganizerEventsIdLeaderboardRouteImport
      parentRoute: typeof AuthenticatedOrganizerEventsIdRoute
    }
    '/_authenticated/organizer/events/$id/jury': {
      id: '/_authenticated/organizer/events/$id/jury'
      path: '/jury'
      fullPath: '/organizer/events/$id/jury'
      preLoaderRoute: typeof AuthenticatedOrganizerEventsIdJuryRouteImport
      parentRoute: typeof AuthenticatedOrganizerEventsIdRoute
    }
    '/_authenticated/organizer/events/$id/judging': {
      id: '/_authenticated/organizer/events/$id/judging'
      path: '/judging'
      fullPath: '/organizer/events/$id/judging'
      preLoaderRoute: typeof AuthenticatedOrganizerEventsIdJudgingRouteImport
      parentRoute: typeof AuthenticatedOrganizerEventsIdRoute
    }
    '/_authenticated/organizer/events/$id/certificates': {
      id: '/_authenticated/organizer/events/$id/certificates'
      path: '/certificates'
      fullPath: '/organizer/events/$id/certificates'
      preLoaderRoute: typeof AuthenticatedOrganizerEventsIdCertificatesRouteImport
      parentRoute: typeof AuthenticatedOrganizerEventsIdRoute
    }
    '/_authenticated/organizer/events/$id/analytics': {
      id: '/_authenticated/organizer/events/$id/analytics'
      path: '/analytics'
      fullPath: '/organizer/events/$id/analytics'
      preLoaderRoute: typeof AuthenticatedOrganizerEventsIdAnalyticsRouteImport
      parentRoute: typeof AuthenticatedOrganizerEventsIdRoute
    }
  }
}

interface AuthenticatedOrganizerEventsIdRouteChildren {
  AuthenticatedOrganizerEventsIdAnalyticsRoute: typeof AuthenticatedOrganizerEventsIdAnalyticsRoute
  AuthenticatedOrganizerEventsIdCertificatesRoute: typeof AuthenticatedOrganizerEventsIdCertificatesRoute
  AuthenticatedOrganizerEventsIdJudgingRoute: typeof AuthenticatedOrganizerEventsIdJudgingRoute
  AuthenticatedOrganizerEventsIdJuryRoute: typeof AuthenticatedOrganizerEventsIdJuryRoute
  AuthenticatedOrganizerEventsIdLeaderboardRoute: typeof AuthenticatedOrganizerEventsIdLeaderboardRoute
  AuthenticatedOrganizerEventsIdRegistrationsRoute: typeof AuthenticatedOrganizerEventsIdRegistrationsRoute
  AuthenticatedOrganizerEventsIdSubmissionsRoute: typeof AuthenticatedOrganizerEventsIdSubmissionsRoute
  AuthenticatedOrganizerEventsIdTeamsRoute: typeof AuthenticatedOrganizerEventsIdTeamsRoute
  AuthenticatedOrganizerEventsIdIndexRoute: typeof AuthenticatedOrganizerEventsIdIndexRoute
}

const AuthenticatedOrganizerEventsIdRouteChildren: AuthenticatedOrganizerEventsIdRouteChildren =
  {
    AuthenticatedOrganizerEventsIdAnalyticsRoute:
      AuthenticatedOrganizerEventsIdAnalyticsRoute,
    AuthenticatedOrganizerEventsIdCertificatesRoute:
      AuthenticatedOrganizerEventsIdCertificatesRoute,
    AuthenticatedOrganizerEventsIdJudgingRoute:
      AuthenticatedOrganizerEventsIdJudgingRoute,
    AuthenticatedOrganizerEventsIdJuryRoute:
      AuthenticatedOrganizerEventsIdJuryRoute,
    AuthenticatedOrganizerEventsIdLeaderboardRoute:
      AuthenticatedOrganizerEventsIdLeaderboardRoute,
    AuthenticatedOrganizerEventsIdRegistrationsRoute:
      AuthenticatedOrganizerEventsIdRegistrationsRoute,
    AuthenticatedOrganizerEventsIdSubmissionsRoute:
      AuthenticatedOrganizerEventsIdSubmissionsRoute,
    AuthenticatedOrganizerEventsIdTeamsRoute:
      AuthenticatedOrganizerEventsIdTeamsRoute,
    AuthenticatedOrganizerEventsIdIndexRoute:
      AuthenticatedOrganizerEventsIdIndexRoute,
  }

const AuthenticatedOrganizerEventsIdRouteWithChildren =
  AuthenticatedOrganizerEventsIdRoute._addFileChildren(
    AuthenticatedOrganizerEventsIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedJuryEventIdRoute: typeof AuthenticatedJuryEventIdRoute
  AuthenticatedOrganizerDashboardRoute: typeof AuthenticatedOrganizerDashboardRoute
  AuthenticatedParticipantEventIdRoute: typeof AuthenticatedParticipantEventIdRoute
  AuthenticatedOrganizerIndexRoute: typeof AuthenticatedOrganizerIndexRoute
  AuthenticatedOrganizerEventsIdRoute: typeof AuthenticatedOrganizerEventsIdRouteWithChildren
  AuthenticatedOrganizerEventsNewRoute: typeof AuthenticatedOrganizerEventsNewRoute
  AuthenticatedOrganizerEventsIndexRoute: typeof AuthenticatedOrganizerEventsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedJuryEventIdRoute: AuthenticatedJuryEventIdRoute,
  AuthenticatedOrganizerDashboardRoute: AuthenticatedOrganizerDashboardRoute,
  AuthenticatedParticipantEventIdRoute: AuthenticatedParticipantEventIdRoute,
  AuthenticatedOrganizerIndexRoute: AuthenticatedOrganizerIndexRoute,
  AuthenticatedOrganizerEventsIdRoute:
    AuthenticatedOrganizerEventsIdRouteWithChildren,
  AuthenticatedOrganizerEventsNewRoute: AuthenticatedOrganizerEventsNewRoute,
  AuthenticatedOrganizerEventsIndexRoute:
    AuthenticatedOrganizerEventsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  AuthFinishRoute: AuthFinishRoute,
  LeaderboardEventIdRoute: LeaderboardEventIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
