// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  // Test-mode stub: when `VITE_TEST_AUTH=true` we allow Playwright tests to set
  // a `TEST_SUPABASE_SESSION` in localStorage and `TEST_USER_ROLE` to control role.
  if (typeof window !== 'undefined' && import.meta.env.VITE_TEST_AUTH === 'true') {
    const testSession = localStorage.getItem('TEST_SUPABASE_SESSION');
    if (testSession) {
      const parsed = JSON.parse(testSession);
      // Minimal mock supabase-like client for tests
      return {
        auth: {
          getSession: async () => ({ data: { session: parsed } }),
          signOut: async () => { localStorage.removeItem('TEST_SUPABASE_SESSION'); return { error: null }; },
          setSession: async (tokens: any) => { localStorage.setItem('TEST_SUPABASE_SESSION', JSON.stringify(tokens)); return { error: null }; },
          signInWithOAuth: async () => ({ data: { url: `${window.location.origin}/auth/finish` }, error: null }),
        },
      } as any;
    }
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

